## For students: change this path to the root of your code
CODEROOT = "/home/liqiangw/workspace/cs222/src/"

#CC = gcc
CC = g++

#CPPFLAGS = -Wall -I$(CODEROOT) -O3  # maximal optimization
CPPFLAGS = -std=c++11 -Wall -I$(CODEROOT) -g   # with debugging info and C++11 supported
